const skills = [
  { path: '../assets/csharp.svg', name: 'C#' },
  { path: '../assets/typescript.svg', name: 'TypeScript' },
  { path: '../assets/javascript.svg', name: 'JavaScript' },
  { path: '../assets/jquery.svg', name: 'jQuery' },
  { path: '../assets/python.svg', name: 'Python' },
  { path: '../assets/php.svg', name: 'Php' },
  { path: '../assets/dotnet.svg', name: '.NET' },
  { path: '../assets/springboot.svg', name: 'Spring Boot' },
  { path: '../assets/express.svg', name: 'Express' },
  { path: '../assets/nestjs.svg', name: 'NestJS' },
  { path: '../assets/angular.svg', name: 'Angular' },
  { path: '../assets/react.svg', name: 'React' },
  { path: '../assets/git.svg', name: 'Versionamento Git' },
  { path: '../assets/docker.svg', name: 'Docker' },
  { path: '../assets/amazonaws.svg', name: 'Amazon AWS' },
  { path: '../assets/sequelize.svg', name: 'ORM Sequelize' },
  { path: '../assets/mongodb.svg', name: 'MongoDB' },
  { path: '../assets/postgresql.svg', name: 'PostgreSQL' },
  { path: '../assets/mysql.svg', name: 'MySQL' },
  { path: '../assets/swagger.svg', name: 'Swagger' },
  { path: '../assets/heroku.svg', name: 'Heroku' },
  { path: '../assets/vercel.svg', name: 'Vercel' },
]

export default skills;
